name: build-release

on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make build-image

      - run: make build-image-push BUILD_TAG=latest
